# Generated by Django 6.0.7 on 2026-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
