# Generated by Django 6.0.7 on 2026-07-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logininfo_email_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='username',
        ),
        migrations.AddField(
            model_name='logininfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
